[package]
name = "asciiVid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "6.0.0"
ascii-canvas = "3.0.0"
image = "0.24.6"
terminal_size = "0.2.6"
